# Generated by Django 5.1.1 on 2024-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_alter_category_post_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='blogsite.post'),
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='blogsite.post'),
        ),
    ]
