# Generated by Django 5.1.1 on 2024-10-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_remove_category_post_remove_tag_post_category_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(related_name='categories', to='blogsite.post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='blogsite.post'),
        ),
    ]
