# Generated by Django 5.1.1 on 2024-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0008_user_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='public_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
